### ISSUE TITLE
Add/remove geometrical parameters

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/BPX#3]
Remove 'Cell height [m]', 'Cell width [m]', 'Cell thickness [m]', 'Cell diameter [m]', and add "Cell volume [m3]", "Cell surface area [m2]" instead. Allow/encourage people to add info on cell form factor, detailed dimensions in the "description" field. This will be enough for lumped thermal models.

**Comment by ejfdickinson** [comment]
I suggest "Cell external surface area" to avoid any possibility of confusion with "Electrode area".
